/*
 *  Copyright (c) 2021-2024 twinlife SA.
 *  SPDX-License-Identifier: AGPL-3.0-only
 *
 *  Contributors:
 *   Romain Kolb (romain.kolb@skyrock.com)
 */

package org.twinlife.twinlife.account;

import androidx.annotation.NonNull;

import org.twinlife.twinlife.BackupInfo;
import org.twinlife.twinlife.Decoder;
import org.twinlife.twinlife.Encoder;
import org.twinlife.twinlife.SerializerException;
import org.twinlife.twinlife.SerializerFactory;
import org.twinlife.twinlife.util.BinaryPacketIQ;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

/**
 * Response IQ for GetAllBackupsIQ, contains info about all backups generated by this account.
 * <p>
 * Schema version 1
 *  Date: 2025/11/21
 * <pre>
 * {
 *  "schemaId":"088b1c90-f9ea-4d1b-8be3-00d6e9b3afe8",
 *  "schemaVersion":"1",
 *
 *  "type":"record",
 *  "name":"OnGetAllBackupsIQ",
 *  "namespace":"org.twinlife.schemas.account",
 *  "super":"org.twinlife.schemas.BinaryPacketIQ"
 *  "fields": [
 *  {"name":"backups", [
 *         {"name":"id", "type": "uuid",
 *          "name": "creationDate", "type": "long"
 *         }
 *      ]}
 *  ]
 * }
 *
 * </pre>
 */
class OnGetAllBackupsIQ extends BinaryPacketIQ {

    private static class OnGetAllBackupsIQSerializer extends BinaryPacketIQSerializer {

        OnGetAllBackupsIQSerializer(UUID schemaId, int schemaVersion) {

            super(schemaId, schemaVersion, OnGetAllBackupsIQ.class);
        }

        @Override
        public void serialize(@NonNull SerializerFactory serializerFactory, @NonNull Encoder encoder,
                              @NonNull Object object) throws SerializerException {
            throw new SerializerException();
        }

        @Override
        @NonNull
        public Object deserialize(@NonNull SerializerFactory serializerFactory,
                                  @NonNull Decoder decoder) throws SerializerException {
            BinaryPacketIQ iq = (BinaryPacketIQ) super.deserialize(serializerFactory, decoder);

            int size = decoder.readInt();
            List<BackupInfo> backups = new ArrayList<>(size);
            for (int i = 0; i < size; i++) {
                backups.add(new BackupInfo(decoder.readUUID(), decoder.readLong()));
            }
            return new OnGetAllBackupsIQ(this, iq, backups);
        }
    }

    @NonNull
    public static BinaryPacketIQSerializer createSerializer(@NonNull UUID schemaId, int schemaVersion) {

        return new OnGetAllBackupsIQSerializer(schemaId, schemaVersion);
    }

    @NonNull
    final List<BackupInfo> backups;

    OnGetAllBackupsIQ(@NonNull BinaryPacketIQSerializer serializer, @NonNull BinaryPacketIQ iq,
                              @NonNull List<BackupInfo> backups) {

        super(serializer, iq);

        this.backups = backups;
    }

    //
    // Override Object methods
    //

    protected void appendTo(@NonNull StringBuilder stringBuilder) {
        super.appendTo(stringBuilder);
        stringBuilder.append("backups=[");
        stringBuilder.append(Arrays.toString(backups.toArray()));
        stringBuilder.append("]");
    }

    @NonNull
    public String toString() {

        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("OnGetAllBackupsIQ\n");
        appendTo(stringBuilder);

        return stringBuilder.toString();

    }
}
